### ISSUE TITLE
permission strings are missing

### ISSUE THREAD

**Issue by iv-enovation** [mouneyrac/moodle-assignsubmission_gradereviews#1]
when listing permissions in Assignment administration -> Permissions the word description of permissions (site:canreviewgrade and site:caneditreviewgrade) are missing so those permissions are described as [[site:caneditreviewgrade]] and [[site:canreviewgrade]]

additionally (and in fact, more importantly), it seems to me that we're dealing with very specific permissions that affect only grade comments in the assignment activity. Would it be possible to choose more specific permission names, ones that do not suggest site-wide effects? Would be "mod/assign:caneditreviewgrade" and "mod/assign:canreviewgrade" more appropriate? 

also, "canreviewgrade" can be possibly captype "read"

**Comment by nwp90** [comment]
This is important for me as the missing strings break behat tests throughout Moodle. I'll get a patch prepared as soon as I'm sure I know what the right thing to do is here - it's easy to just fix the strings, but to fix the naming and make sure existing setups get migrated to the fixed version etc. will take a little more time. Alternatively, if anyone else is able to do it quicker.... :)

**Comment by nwp90** [comment]
When it comes to adding strings for these capabilities, I notice that they don't seem particularly well-named in the first place. I'm guessing this code has evolved a bit over time, and the capabilities no longer do what was originally envisioned.

**Comment by mouneyrac** [comment]
I added some translation. Feel free to send a pull request with better cap name.
