### ISSUE TITLE
Event class specified breaks Event Monitoring

### ISSUE THREAD

**Issue by mkpelletier** [mouneyrac/moodle-assignsubmission_gradereviews#2]
Moodle Version 3.0
Plugin version 1.0 (Build: 2016042200)

When attempting to update event monitoring rules, I get a 500 error with this plugin.  php_errors.log has the following:

PHP Fatal error:  Class 'core\event\gradereview_created' not found in /storage/www/mysats/mod/assign/submission/gradereviews/classes/event/gradereview_created.php on line 36

OR

PHP Fatal error:  Class 'core\event\admincomment_deleted' not found in /storage/www/mysats/mod/assign/submission/admincomments/classes/event/admincomment_deleted.php on line 36

I believe the core event observer should be '\core\event\comment_created' and '\core\event\comment_deleted' as per https://docs.moodle.org/dev/Event_2

**Comment by mouneyrac** [comment]
Closing as the fix has been merged.
